/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package foodchain;

import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import utils.Utils;

/**
 *
 * @author manso
 */
public class FoodCoin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FoodCoin.class.getName());

    FoodUser user;
    RemoteNodeInterface remoteObject;

    /**
     * Creates new form TemparCoin
     */
    public FoodCoin() {
        initComponents();
    }

    public FoodCoin(FoodUser user, RemoteNodeInterface remoteObject) {
        this();
        this.user = user;
        this.remoteObject = remoteObject;
        txtSenderPublicKey.setText(Utils.toString(user.getPublicKey().getEncoded()));
        txtTransactionSender.setText(user.getUserName());
    }

    public List<FoodTransaction> getTransactions() {
        List<FoodTransaction> transactions = new ArrayList<>();
        try {
            List<String> txtList = remoteObject.getRegisteredTransactions();
            for (String txt : txtList) {
                try {
                    Object obj = utils.Utils.base64ToObject(txt);
                    // Suporta FoodTransaction
                    if (obj instanceof FoodTransaction) {
                        transactions.add((FoodTransaction) obj);
                    }
                } catch (Exception e) {
                    // Ignora transações que não consegue ler
                }
            }
        } catch (RemoteException ex) {
            System.getLogger(FoodCoin.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        return transactions;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtTransactionSender = new javax.swing.JTextField();
        txtTransactionPassword = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        txtSenderPublicKey = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        txtSignature = new javax.swing.JTextField();
        btSign = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        txtTransactionReceiver = new javax.swing.JTextField();
        txtReceiverPublicKey = new javax.swing.JLabel();
        txtTransactionvalue = new javax.swing.JTextField();
        btAddTransaction = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btGetTransactions = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTransactions = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Sender"));

        txtTransactionSender.setText("master");
        txtTransactionSender.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));

        txtTransactionPassword.setText("123qwe");
        txtTransactionPassword.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));

        jTextField1.setEditable(false);
        jTextField1.setText("jTextField1");
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Balance"));

        txtSenderPublicKey.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtSenderPublicKey.setForeground(new java.awt.Color(255, 0, 51));
        txtSenderPublicKey.setText("public key");
        txtSenderPublicKey.setBorder(javax.swing.BorderFactory.createTitledBorder("public Key"));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTransactionSender, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTransactionPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSenderPublicKey, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(221, 221, 221)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTransactionSender, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(txtTransactionPassword, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenderPublicKey, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Transaction"));

        txtSignature.setEditable(false);
        txtSignature.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtSignature.setForeground(new java.awt.Color(255, 51, 51));
        txtSignature.setBorder(javax.swing.BorderFactory.createTitledBorder("Signature"));

        btSign.setText("Sign");
        btSign.addActionListener(this::btSignActionPerformed);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btSign, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSignature, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSignature, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(btSign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Receiver"));

        txtTransactionReceiver.setText("joana");
        txtTransactionReceiver.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));

        txtReceiverPublicKey.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtReceiverPublicKey.setForeground(new java.awt.Color(255, 0, 51));
        txtReceiverPublicKey.setText("public key");
        txtReceiverPublicKey.setBorder(javax.swing.BorderFactory.createTitledBorder("public Key"));

        txtTransactionvalue.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtTransactionvalue.setForeground(new java.awt.Color(255, 51, 51));
        txtTransactionvalue.setText("10.0");
        txtTransactionvalue.setBorder(javax.swing.BorderFactory.createTitledBorder("Value"));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTransactionReceiver, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTransactionvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(txtReceiverPublicKey, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTransactionvalue, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(txtTransactionReceiver, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReceiverPublicKey, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btAddTransaction.setText("Add Transaction");
        btAddTransaction.addActionListener(this::btAddTransactionActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAddTransaction)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Templar Coin", jPanel6);

        jPanel1.setLayout(new java.awt.BorderLayout());

        btGetTransactions.setText("GetTransactions");
        btGetTransactions.addActionListener(this::btGetTransactionsActionPerformed);
        jPanel1.add(btGetTransactions, java.awt.BorderLayout.NORTH);

        txtTransactions.setColumns(20);
        txtTransactions.setRows(5);
        jScrollPane1.setViewportView(txtTransactions);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Transactions", jPanel1);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignActionPerformed
        try {
            String txtSender = txtTransactionSender.getText();
            String pass = new String(txtTransactionPassword.getPassword());
            String txtReceiver = txtTransactionReceiver.getText();
            double value = Double.parseDouble(txtTransactionvalue.getText());
            
            // Criar produto simples a partir do valor
            long now = System.currentTimeMillis();
            FoodProduct product = new FoodProduct(
                "Produto-" + txtSender, 
                "LOTE-" + now,
                "Geral",
                value,
                "units",
                txtSender,
                now,
                now + 30L * 24 * 60 * 60 * 1000
            );
            
            //criar a transação FOOD
            FoodTransaction t = new FoodTransaction(txtSender, txtReceiver, product, pass);

            //mostrar a transação
            txtSenderPublicKey.setText(Utils.toString(t.getSender().getEncoded()));
            txtReceiverPublicKey.setText(Utils.toString(t.getReceiver().getEncoded()));
            txtSignature.setText(Utils.toString(t.getSignature()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Sign", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btSignActionPerformed

    private void btAddTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddTransactionActionPerformed
        try {
            String txtSender = txtTransactionSender.getText();
            String pass = new String(txtTransactionPassword.getPassword());
            String txtReceiver = txtTransactionReceiver.getText();
            double value = Double.parseDouble(txtTransactionvalue.getText());
            
            // Criar produto a partir do valor
            long now = System.currentTimeMillis();
            FoodProduct product = new FoodProduct(
                "Produto-" + txtSender, 
                "LOTE-" + now,
                "Geral",
                value,
                "units",
                txtSender,
                now,
                now + 30L * 24 * 60 * 60 * 1000
            );
            
            //criar a transação FOOD
            FoodTransaction t = new FoodTransaction(txtSender, txtReceiver, product, pass);
            remoteObject.addTransaction(utils.Utils.ObjectToBase64(t));
            txtReceiverPublicKey.setText("");
            txtTransactionReceiver.setText("");
            txtTransactionvalue.setText("");
            JOptionPane.showMessageDialog(this, "Food Transaction registered\nProduct ID: " + product.getProductId(), "Transaction", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "New Block", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btAddTransactionActionPerformed

    private void btGetTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGetTransactionsActionPerformed
        List<FoodTransaction> tr = getTransactions();
        StringBuilder txt = new StringBuilder();
        txt.append("=== TRANSAÇÕES FOOD CHAIN ===\n\n");
        int count = 0;
        for (FoodTransaction t : tr) {
            count++;
            txt.append(count).append(". ");
            if (t.isCreateTransaction()) {
                txt.append("[CRIAR] ");
            } else {
                txt.append("[TRANSFERIR] ");
            }
            txt.append(t.getTxtSender());
            if (!t.isCreateTransaction()) {
                txt.append(" → ").append(t.getTxtReceiver());
            }
            txt.append("\n");
            txt.append("   Product: ").append(t.getProduct().getProductName());
            txt.append(" [").append(t.getProduct().getProductId()).append("]\n");
            txt.append("   Estação: ").append(t.getProduct().getCurrentStation());
            txt.append(" | Status: ").append(t.getProduct().getStatus()).append("\n");
            txt.append("\n");
        }
        if (count == 0) {
            txt.append("Nenhuma transação encontrada.\n");
        }
        txtTransactions.setText(txt.toString());
    }//GEN-LAST:event_btGetTransactionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FoodCoin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddTransaction;
    private javax.swing.JButton btGetTransactions;
    private javax.swing.JButton btSign;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel txtReceiverPublicKey;
    private javax.swing.JLabel txtSenderPublicKey;
    private javax.swing.JTextField txtSignature;
    private javax.swing.JPasswordField txtTransactionPassword;
    private javax.swing.JTextField txtTransactionReceiver;
    private javax.swing.JTextField txtTransactionSender;
    private javax.swing.JTextArea txtTransactions;
    private javax.swing.JTextField txtTransactionvalue;
    // End of variables declaration//GEN-END:variables
}
