/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package foodchain;

import java.util.List;
import javax.swing.JOptionPane;
import utils.RMI;

/**
 *
 * @author manso
 */
public class TemplarLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TemplarLogin.class.getName());

    /**
     * Creates new form Login
     */
    public TemplarLogin() {
        initComponents();
        setTitle("Food Chain - Login");
        displayUsers();
    }

    public void displayUsers() {
        List<FoodUser> lst = FoodUser.getUserList();
        StringBuilder txt = new StringBuilder();
        for (FoodUser u : lst) {
            txt.append(u.getUserName()).append("\n");
        }
        txtUsers.setText(txt.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtNodeAdress = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtLoginUser = new javax.swing.JTextField();
        txtLoginPass = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtRegisterUsername = new javax.swing.JTextField();
        txtRegisterPass1 = new javax.swing.JPasswordField();
        txtRegisterPass2 = new javax.swing.JPasswordField();
        cmbUserType = new javax.swing.JComboBox<>();
        brRegister = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtUsers = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNodeAdress.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtNodeAdress.setText("//10.10.209.12:10002/remoteNode");
        txtNodeAdress.setBorder(javax.swing.BorderFactory.createTitledBorder("Node Adress"));

        txtLoginUser.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtLoginUser.setText("manso");
        txtLoginUser.setBorder(javax.swing.BorderFactory.createTitledBorder("Username"));

        txtLoginPass.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtLoginPass.setText("123qwe");
        txtLoginPass.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtLoginPass, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtLoginUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoginPass, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btLogin.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/templarCoin_2.png"))); // NOI18N
        btLogin.setText("Login");
        btLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btLogin.addActionListener(this::btLoginActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNodeAdress)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(txtNodeAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Login", jPanel1);

        jPanel6.setLayout(new java.awt.GridLayout(3, 1, 5, 0));

        txtRegisterUsername.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtRegisterUsername.setBorder(javax.swing.BorderFactory.createTitledBorder("Username"));
        jPanel6.add(txtRegisterUsername);

        txtRegisterPass1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtRegisterPass1.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));
        jPanel6.add(txtRegisterPass1);

        txtRegisterPass2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtRegisterPass2.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));
        jPanel6.add(txtRegisterPass2);
        
        cmbUserType.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        cmbUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produtor", "Armazém", "Distribuidor", "Loja" }));
        cmbUserType.setSelectedIndex(0);
        javax.swing.JPanel typePanel = new javax.swing.JPanel();
        typePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Utilizador"));
        typePanel.setLayout(new java.awt.BorderLayout());
        typePanel.add(cmbUserType, java.awt.BorderLayout.CENTER);
        jPanel6.add(typePanel);

        brRegister.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        brRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/templarCoin_2.png"))); // NOI18N
        brRegister.setText("Register");
        brRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        brRegister.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        brRegister.addActionListener(this::brRegisterActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Register", jPanel2);

        jPanel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel3FocusGained(evt);
            }
        });
        jPanel3.setLayout(new java.awt.BorderLayout());

        txtUsers.setEditable(false);
        txtUsers.setColumns(20);
        txtUsers.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtUsers.setRows(5);
        jScrollPane1.setViewportView(txtUsers);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Users", jPanel3);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brRegisterActionPerformed
        String pass1 = new String(txtRegisterPass1.getPassword());
        String pass2 = new String(txtRegisterPass2.getPassword());
        if (!pass1.equals(pass2)) {
            JOptionPane.showConfirmDialog(this, "As passwords não são iguais", "Regoster", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            FoodUser u = FoodUser.login(txtRegisterUsername.getText());
            JOptionPane.showConfirmDialog(this, "O utilizador já existe", "Regoster", JOptionPane.ERROR_MESSAGE);
            return;
        } catch (Exception ex) {
        }
        try {
            // Obter o tipo de utilizador selecionado (cmbUserType.getSelectedIndex() + 1 porque começa em 0)
            int userType = cmbUserType.getSelectedIndex() + 1; // 1=Produtor, 2=Armazém, 3=Distribuidor, 4=Loja
            FoodUser.register(txtRegisterUsername.getText(), pass2, userType);
            displayUsers();
            JOptionPane.showMessageDialog(this, "Utilizador registado com sucesso! Tipo: " + FoodUser.TYPE_NAMES[userType], "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Login", JOptionPane.ERROR_MESSAGE);

            System.getLogger(TemplarLogin.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }//GEN-LAST:event_brRegisterActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        try {
            FoodUser user = FoodUser.login(txtLoginUser.getText(), new String(txtLoginPass.getPassword()));
            RemoteNodeInterface node = (RemoteNodeInterface) RMI.getRemote(txtNodeAdress.getText());
            
            // Abrir GUI da Food Chain em vez da TemplarCoin
            FoodChainGUI gui = new FoodChainGUI(user, node);
            this.setVisible(false);
            gui.setVisible(true);
                     
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Login", JOptionPane.ERROR_MESSAGE);
            System.getLogger(TemplarLogin.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btLoginActionPerformed

    private void jPanel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel3FocusGained
        displayUsers();
    }//GEN-LAST:event_jPanel3FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TemplarLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brRegister;
    private javax.swing.JButton btLogin;
    private javax.swing.JComboBox<String> cmbUserType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPasswordField txtLoginPass;
    private javax.swing.JTextField txtLoginUser;
    private javax.swing.JTextField txtNodeAdress;
    private javax.swing.JPasswordField txtRegisterPass1;
    private javax.swing.JPasswordField txtRegisterPass2;
    private javax.swing.JTextField txtRegisterUsername;
    private javax.swing.JTextArea txtUsers;
    // End of variables declaration//GEN-END:variables
}
